[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "authstar"
authors = [{name = "John Wagenleitner", email = "johnwa@mail.fresnostate.edu"}]
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["Authentication", "ASGI"]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: Apache Software License",
    "Intended Audience :: Developers",
]
dynamic = ["version", "description"]
requires-python = ">=3.11"
dependencies = []

[project.urls]
Home = "https://github.com/jowage58/authstar"
Source = "https://github.com/jowage58/authstar"

[dependency-groups]
dev = [
    "async-lru>=2.0.4",
    "fastapi>=0.115.4",
    "itsdangerous>=2.2.0",
    "joserfc>=1.0.0",
    "mypy>=1.13.0",
    "pydantic>=2.9.2",
    "pytest>=8.3.3",
    "python-multipart>=0.0.16",
    "starlette>=0.41.2",
    "uvicorn[standard]>=0.32.0",
]

[tool.mypy]
packages = ["authstar", "example"]
strict = true
warn_unreachable = true

[tool.ruff]
target-version = "py311"
extend-exclude = [".*"]

[tool.ruff.format]
preview = true

[tool.ruff.lint]
select = [
    "A",  # shadowing builtins
    "ARG",  # unused arguments
    "ASYNC",  # async checks
    "B",  # bugbear
    "C4",  # comprehensions
    "DTZ",  # checks for naive datetimes
    "E",  # pycodestyle (errors)
    "ERA",  # eradicate (commented out code)
    "F",  # Pyflakes
    "FBT",  # boolean trap
    "I",   # isort
    "ISC",  # Implicit String Concat
    "N",  # pep8-naming
    "PIE",  # misc lints
    "PL",  # Pylint
    "PT",  # Pytest
    "PTH",  # favor pahtlib.Path
    "RET",  # returns
    "RUF",  # Ruff-specific rules
    "S",  # bandit
    "SIM",  # simplify
    "T20",  # print statements
    "TRY",  # tryceratops
    "UP",  # pyupgrade
    "W",  # pycodestyle (warnings)
]
ignore = ["ISC001"]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["S101", "S105"]

[tool.ruff.lint.pylint]
max-args = 10
